[package]
name = "mutisig"
version = "1.0.0"
authors = []

[addresses]
multiture = "0x5d7f79da44885dfd543f81139cff25fb43121e7ae03ebd720f9ac9e6449dd1a5"
MAN = "0x5d7f79da44885dfd543f81139cff25fb43121e7ae03ebd720f9ac9e6449dd1a5"
FACTORY = "0x6e3e09ab7fd0145d7befc0c68d6944ddc1a90fd45b8a6d28c76d8c48bed676b0"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosToken]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]


